In [16]:
import pandas as pd
import yfinance as yf
import numpy as np
from plotly.subplots import make_subplots
import plotly.graph_objects as go

In [17]:
data = yf.download("AAPL",start='2025-01-01')
data.columns = data.columns.get_level_values(0)  # flatten to single level
data

[*********************100%***********************]  1 of 1 completed

Price            Close        High         Low        Open    Volume
Date
2025-01-02  242.301926  247.518596  240.284814  247.349662  55740700
2025-01-03  241.815048  242.629835  240.354379  241.815048  40244100
2025-01-06  243.444626  245.759836  241.656050  242.759004  45045600
2025-01-07  240.672348  243.991141  239.817807  241.437449  40856000
2025-01-08  241.159241  242.162839  238.526070  240.384194  37628900
...                ...         ...         ...         ...       ...
2026-07-01  294.380005  296.589996  289.200012  293.440002  50164200
2026-07-02  308.630005  309.420013  293.679993  294.119995  75352800
2026-07-06  312.660004  314.200012  307.000000  307.359985  53590000
2026-07-07  310.660004  315.480011  310.149994  315.290009  42426500
2026-07-08  309.084991  312.000000  307.051514  311.660004   9843637

[378 rows x 5 columns]

In [18]:
data['Returns'] = data['Close'].pct_change()
data = data.dropna()
data

Price            Close        High         Low        Open    Volume   Returns
Date
2025-01-03  241.815048  242.629835  240.354379  241.815048  40244100 -0.002009
2025-01-06  243.444626  245.759836  241.656050  242.759004  45045600  0.006739
2025-01-07  240.672348  243.991141  239.817807  241.437449  40856000 -0.011388
2025-01-08  241.159241  242.162839  238.526070  240.384194  37628900  0.002023
2025-01-10  235.346390  238.635374  231.520825  238.486317  61710900 -0.024104
...                ...         ...         ...         ...       ...       ...
2026-07-01  294.380005  296.589996  289.200012  293.440002  50164200  0.017349
2026-07-02  308.630005  309.420013  293.679993  294.119995  75352800  0.048407
2026-07-06  312.660004  314.200012  307.000000  307.359985  53590000  0.013058
2026-07-07  310.660004  315.480011  310.149994  315.290009  42426500 -0.006397
2026-07-08  309.084991  312.000000  307.051514  311.660004   9843637 -0.005070

[377 rows x 6 columns]

# **SMA ANALYSIS**

In [19]:
data['SMA_20'] = data['Close'].rolling(20).mean()
data['SMA_50'] = data['Close'].rolling(50).mean()

/var/folders/3f/1m46pnxd04q1x1ktf6jcs_fr0000gn/T/ipykernel_25177/2929945010.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['SMA_20'] = data['Close'].rolling(20).mean()
/var/folders/3f/1m46pnxd04q1x1ktf6jcs_fr0000gn/T/ipykernel_25177/2929945010.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['SMA_50'] = data['Close'].rolling(50).mean()

In [20]:
data

Price,Close,High,Low,Open,Volume,Returns,SMA_20,SMA_50
Date,,,,,,,,
2025-01-03,241.815048,242.629835,240.354379,241.815048,40244100,-0.002009,NaN,NaN
2025-01-06,243.444626,245.759836,241.656050,242.759004,45045600,0.006739,NaN,NaN
2025-01-07,240.672348,243.991141,239.817807,241.437449,40856000,-0.011388,NaN,NaN
2025-01-08,241.159241,242.162839,238.526070,240.384194,37628900,0.002023,NaN,NaN
2025-01-10,235.346390,238.635374,231.520825,238.486317,61710900,-0.024104,NaN,NaN
...,...,...,...,...,...,...,...,...
2026-07-01,294.380005,296.589996,289.200012,293.440002,50164200,0.017349,294.884000,292.602499
2026-07-02,308.630005,309.420013,293.679993,294.119995,75352800,0.048407,294.802499,293.456599
2026-07-06,312.660004,314.200012,307.000000,307.359985,53590000,0.013058,294.873999,294.251427
2026-07-07,310.660004,315.480011,310.149994,315.290009,42426500,-0.006397,295.039999,295.001061
2026-07-08,309.084991,312.000000,307.051514,311.660004,9843637,-0.005070,295.417249,295.766551

In [21]:
data.dropna(inplace=True)

/var/folders/3f/1m46pnxd04q1x1ktf6jcs_fr0000gn/T/ipykernel_25177/1368182302.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.dropna(inplace=True)

In [22]:
data

Price,Close,High,Low,Open,Volume,Returns,SMA_20,SMA_50
Date,,,,,,,,
2025-03-18,211.572098,214.019159,210.378408,213.034373,42432400,-0.006122,231.235703,232.228111
2025-03-19,214.108688,217.610176,212.626514,213.094045,54385400,0.011989,229.761990,231.673984
2025-03-20,212.974716,216.346898,211.104592,212.865294,48862900,-0.005296,228.183829,231.064586
2025-03-21,217.122772,217.689768,210.169506,210.448033,94127800,0.019477,226.826999,230.593594
2025-03-24,219.569839,220.315897,217.431146,219.838425,44299500,0.011270,225.515428,230.161806
...,...,...,...,...,...,...,...,...
2026-07-01,294.380005,296.589996,289.200012,293.440002,50164200,0.017349,294.884000,292.602499
2026-07-02,308.630005,309.420013,293.679993,294.119995,75352800,0.048407,294.802499,293.456599
2026-07-06,312.660004,314.200012,307.000000,307.359985,53590000,0.013058,294.873999,294.251427
2026-07-07,310.660004,315.480011,310.149994,315.290009,42426500,-0.006397,295.039999,295.001061
2026-07-08,309.084991,312.000000,307.051514,311.660004,9843637,-0.005070,295.417249,295.766551

In [23]:
fig = make_subplots(rows=2,cols=1)
fig.add_trace(go.Candlestick(x=data.index,open=data['Open'],high=data['High'],low=data['Low'],close=data['Close'],name='Closing Price'),row=1,col=1)
fig.add_trace(go.Scatter(x=data.index,y=data['SMA_20'],name='SMA_20',mode='lines'),row=1,col=1)
fig.add_trace(go.Scatter(x=data.index,y=data['SMA_50'],name='SMA_50',mode='lines'),row=1,col=1)
fig.update_layout(
    height = 600,
    width=800,
    title='AAPL Price with Moving Averages',
    xaxis_title='Date',
    yaxis_title='Price (USD)',
    template='plotly_dark'  # looks clean
)
fig.add_trace(go.Bar(x=data.index,y=data['Volume'],name='Volume'),row=2,col=1)
fig.show()

# **TENDENCIES NOTED FROM THE CHART:**
1)The price tends to go up when the SMA20 marks overtakes SMA50.This was noticed on **17 July 2025** when the overall trend was upwards all the way until **6 January 2026** when the SMA divergence finished

2)The price tends to 'bounce' off the SMA50 line which proves the hypothesis of SMA having an impact on the price action

In [24]:
data

Price,Close,High,Low,Open,Volume,Returns,SMA_20,SMA_50
Date,,,,,,,,
2025-03-18,211.572098,214.019159,210.378408,213.034373,42432400,-0.006122,231.235703,232.228111
2025-03-19,214.108688,217.610176,212.626514,213.094045,54385400,0.011989,229.761990,231.673984
2025-03-20,212.974716,216.346898,211.104592,212.865294,48862900,-0.005296,228.183829,231.064586
2025-03-21,217.122772,217.689768,210.169506,210.448033,94127800,0.019477,226.826999,230.593594
2025-03-24,219.569839,220.315897,217.431146,219.838425,44299500,0.011270,225.515428,230.161806
...,...,...,...,...,...,...,...,...
2026-07-01,294.380005,296.589996,289.200012,293.440002,50164200,0.017349,294.884000,292.602499
2026-07-02,308.630005,309.420013,293.679993,294.119995,75352800,0.048407,294.802499,293.456599
2026-07-06,312.660004,314.200012,307.000000,307.359985,53590000,0.013058,294.873999,294.251427
2026-07-07,310.660004,315.480011,310.149994,315.290009,42426500,-0.006397,295.039999,295.001061
2026-07-08,309.084991,312.000000,307.051514,311.660004,9843637,-0.005070,295.417249,295.766551

# **VOLATILITY ANALYSIS**

In [25]:
data['Volatility'] = data['Returns'].rolling(20).std() * (252 ** 0.5)
data.dropna(inplace=True)
data

/var/folders/3f/1m46pnxd04q1x1ktf6jcs_fr0000gn/T/ipykernel_25177/4174629229.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Volatility'] = data['Returns'].rolling(20).std() * (252 ** 0.5)
/var/folders/3f/1m46pnxd04q1x1ktf6jcs_fr0000gn/T/ipykernel_25177/4174629229.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.dropna(inplace=True)

Price,Close,High,Low,Open,Volume,Returns,SMA_20,SMA_50,Volatility
Date,,,,,,,,,
2025-04-14,201.455566,211.820797,200.102714,210.328681,101352900,0.022054,207.536428,222.618188,0.792022
2025-04-15,201.077560,202.440355,198.749863,200.799033,51343900,-0.001876,207.011701,222.108489,0.791844
2025-04-16,193.248917,199.645113,191.358894,197.317416,59732400,-0.038933,205.968713,221.347026,0.801010
2025-04-17,195.944672,197.784954,193.398129,196.163517,52164700,0.013950,205.117210,220.646036,0.803486
2025-04-21,192.144730,192.781365,188.812332,192.254152,46742500,-0.019393,203.868308,219.854142,0.800923
...,...,...,...,...,...,...,...,...,...
2026-07-01,294.380005,296.589996,289.200012,293.440002,50164200,0.017349,294.884000,292.602499,0.342462
2026-07-02,308.630005,309.420013,293.679993,294.119995,75352800,0.048407,294.802499,293.456599,0.384440
2026-07-06,312.660004,314.200012,307.000000,307.359985,53590000,0.013058,294.873999,294.251427,0.387112
2026-07-07,310.660004,315.480011,310.149994,315.290009,42426500,-0.006397,295.039999,295.001061,0.384992
2026-07-08,309.084991,312.000000,307.051514,311.660004,9843637,-0.005070,295.417249,295.766551,0.378695

In [26]:
fig = go.Figure()

fig.add_trace(go.Scatter(x=data.index, y=data['Close'],
              name='Close', mode='lines'))

fig.add_trace(go.Scatter(x=data.index, y=data['Volatility'],
              name='Volatility (20d)', mode='lines', yaxis='y2'))

fig.update_layout(
    title='AAPL Price & Volatility',
    yaxis2=dict(overlaying='y', side='right'),  # second y-axis
    template='plotly_dark'
)
fig.show()


# **TENDENCIES SPOTTED**

1)The price tends to go up after a drop in volatility

2)The trend becomes stronger when volatility consolidates

3)Volatility spikes usually happen after a big price drop