In [2]:
import pandas as pd
import yfinance as yf
import numpy as np
from plotly.subplots import make_subplots
import plotly.graph_objects as go

In [3]:
data = yf.download("AAPL",start='2025-01-01')
data.columns = data.columns.get_level_values(0)  # flatten to single level
data

[*********************100%***********************]  1 of 1 completed

Price            Close        High         Low        Open    Volume
Date
2025-01-02  242.301926  247.518596  240.284814  247.349662  55740700
2025-01-03  241.815018  242.629804  240.354349  241.815018  40244100
2025-01-06  243.444611  245.759820  241.656035  242.758989  45045600
2025-01-07  240.672318  243.991110  239.817777  241.437418  40856000
2025-01-08  241.159225  242.162823  238.526055  240.384178  37628900
...                ...         ...         ...         ...       ...
2026-07-01  294.380005  296.589996  289.200012  293.440002  50164200
2026-07-02  308.630005  309.420013  293.679993  294.119995  75352800
2026-07-06  312.660004  314.200012  307.000000  307.359985  53590000
2026-07-07  310.660004  315.480011  310.149994  315.290009  42490000
2026-07-08  313.390015  314.820007  307.049988  311.910004  41299400

[378 rows x 5 columns]

In [4]:
data['Returns'] = data['Close'].pct_change()
data = data.dropna()
data

Price            Close        High         Low        Open    Volume   Returns
Date
2025-01-03  241.815018  242.629804  240.354349  241.815018  40244100 -0.002010
2025-01-06  243.444611  245.759820  241.656035  242.758989  45045600  0.006739
2025-01-07  240.672318  243.991110  239.817777  241.437418  40856000 -0.011388
2025-01-08  241.159225  242.162823  238.526055  240.384178  37628900  0.002023
2025-01-10  235.346375  238.635359  231.520810  238.486302  61710900 -0.024104
...                ...         ...         ...         ...       ...       ...
2026-07-01  294.380005  296.589996  289.200012  293.440002  50164200  0.017349
2026-07-02  308.630005  309.420013  293.679993  294.119995  75352800  0.048407
2026-07-06  312.660004  314.200012  307.000000  307.359985  53590000  0.013058
2026-07-07  310.660004  315.480011  310.149994  315.290009  42490000 -0.006397
2026-07-08  313.390015  314.820007  307.049988  311.910004  41299400  0.008788

[377 rows x 6 columns]

# **SMA ANALYSIS**

In [5]:
data['SMA_20'] = data['Close'].rolling(20).mean()
data['SMA_50'] = data['Close'].rolling(50).mean()

/var/folders/3f/1m46pnxd04q1x1ktf6jcs_fr0000gn/T/ipykernel_30835/2929945010.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['SMA_20'] = data['Close'].rolling(20).mean()
/var/folders/3f/1m46pnxd04q1x1ktf6jcs_fr0000gn/T/ipykernel_30835/2929945010.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['SMA_50'] = data['Close'].rolling(50).mean()

In [6]:
data

Price,Close,High,Low,Open,Volume,Returns,SMA_20,SMA_50
Date,,,,,,,,
2025-01-03,241.815018,242.629804,240.354349,241.815018,40244100,-0.002010,NaN,NaN
2025-01-06,243.444611,245.759820,241.656035,242.758989,45045600,0.006739,NaN,NaN
2025-01-07,240.672318,243.991110,239.817777,241.437418,40856000,-0.011388,NaN,NaN
2025-01-08,241.159225,242.162823,238.526055,240.384178,37628900,0.002023,NaN,NaN
2025-01-10,235.346375,238.635359,231.520810,238.486302,61710900,-0.024104,NaN,NaN
...,...,...,...,...,...,...,...,...
2026-07-01,294.380005,296.589996,289.200012,293.440002,50164200,0.017349,294.884000,292.602499
2026-07-02,308.630005,309.420013,293.679993,294.119995,75352800,0.048407,294.802499,293.456599
2026-07-06,312.660004,314.200012,307.000000,307.359985,53590000,0.013058,294.873999,294.251427
2026-07-07,310.660004,315.480011,310.149994,315.290009,42490000,-0.006397,295.039999,295.001061
2026-07-08,313.390015,314.820007,307.049988,311.910004,41299400,0.008788,295.632500,295.852651

In [7]:
data.dropna(inplace=True)

/var/folders/3f/1m46pnxd04q1x1ktf6jcs_fr0000gn/T/ipykernel_30835/1368182302.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.dropna(inplace=True)

In [8]:
data

Price,Close,High,Low,Open,Volume,Returns,SMA_20,SMA_50
Date,,,,,,,,
2025-03-18,211.572098,214.019159,210.378408,213.034373,42432400,-0.006122,231.235704,232.228109
2025-03-19,214.108688,217.610176,212.626514,213.094045,54385400,0.011989,229.761990,231.673983
2025-03-20,212.974701,216.346883,211.104577,212.865278,48862900,-0.005296,228.183828,231.064585
2025-03-21,217.122772,217.689768,210.169506,210.448033,94127800,0.019477,226.826997,230.593594
2025-03-24,219.569855,220.315913,217.431161,219.838440,44299500,0.011271,225.515428,230.161806
...,...,...,...,...,...,...,...,...
2026-07-01,294.380005,296.589996,289.200012,293.440002,50164200,0.017349,294.884000,292.602499
2026-07-02,308.630005,309.420013,293.679993,294.119995,75352800,0.048407,294.802499,293.456599
2026-07-06,312.660004,314.200012,307.000000,307.359985,53590000,0.013058,294.873999,294.251427
2026-07-07,310.660004,315.480011,310.149994,315.290009,42490000,-0.006397,295.039999,295.001061
2026-07-08,313.390015,314.820007,307.049988,311.910004,41299400,0.008788,295.632500,295.852651

In [9]:
fig = make_subplots(rows=2,cols=1)
fig.add_trace(go.Candlestick(x=data.index,open=data['Open'],high=data['High'],low=data['Low'],close=data['Close'],name='Closing Price'),row=1,col=1)
fig.add_trace(go.Scatter(x=data.index,y=data['SMA_20'],name='SMA_20',mode='lines'),row=1,col=1)
fig.add_trace(go.Scatter(x=data.index,y=data['SMA_50'],name='SMA_50',mode='lines'),row=1,col=1)
fig.update_layout(
    height = 600,
    width=800,
    title='AAPL Price with Moving Averages',
    xaxis_title='Date',
    yaxis_title='Price (USD)',
    template='plotly_dark'  # looks clean
)
fig.add_trace(go.Bar(x=data.index,y=data['Volume'],name='Volume'),row=2,col=1)
fig.show()

# **TENDENCIES NOTED FROM THE CHART:**
1)The price tends to go up when the SMA20 marks overtakes SMA50.This was noticed on **17 July 2025** when the overall trend was upwards all the way until **6 January 2026** when the SMA divergence finished

2)The price tends to 'bounce' off the SMA50 line which proves the hypothesis of SMA having an impact on the price action

In [10]:
data

Price,Close,High,Low,Open,Volume,Returns,SMA_20,SMA_50
Date,,,,,,,,
2025-03-18,211.572098,214.019159,210.378408,213.034373,42432400,-0.006122,231.235704,232.228109
2025-03-19,214.108688,217.610176,212.626514,213.094045,54385400,0.011989,229.761990,231.673983
2025-03-20,212.974701,216.346883,211.104577,212.865278,48862900,-0.005296,228.183828,231.064585
2025-03-21,217.122772,217.689768,210.169506,210.448033,94127800,0.019477,226.826997,230.593594
2025-03-24,219.569855,220.315913,217.431161,219.838440,44299500,0.011271,225.515428,230.161806
...,...,...,...,...,...,...,...,...
2026-07-01,294.380005,296.589996,289.200012,293.440002,50164200,0.017349,294.884000,292.602499
2026-07-02,308.630005,309.420013,293.679993,294.119995,75352800,0.048407,294.802499,293.456599
2026-07-06,312.660004,314.200012,307.000000,307.359985,53590000,0.013058,294.873999,294.251427
2026-07-07,310.660004,315.480011,310.149994,315.290009,42490000,-0.006397,295.039999,295.001061
2026-07-08,313.390015,314.820007,307.049988,311.910004,41299400,0.008788,295.632500,295.852651

# **VOLATILITY ANALYSIS**

In [11]:
data['Volatility'] = data['Returns'].rolling(20).std() * (252 ** 0.5)
data.dropna(inplace=True)
data

/var/folders/3f/1m46pnxd04q1x1ktf6jcs_fr0000gn/T/ipykernel_30835/4174629229.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Volatility'] = data['Returns'].rolling(20).std() * (252 ** 0.5)
/var/folders/3f/1m46pnxd04q1x1ktf6jcs_fr0000gn/T/ipykernel_30835/4174629229.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.dropna(inplace=True)

Price,Close,High,Low,Open,Volume,Returns,SMA_20,SMA_50,Volatility
Date,,,,,,,,,
2025-04-14,201.455551,211.820781,200.102699,210.328665,101352900,0.022054,207.536426,222.618187,0.792023
2025-04-15,201.077545,202.440340,198.749848,200.799018,51343900,-0.001876,207.011698,222.108489,0.791845
2025-04-16,193.248932,199.645129,191.358909,197.317431,59732400,-0.038933,205.968710,221.347026,0.801011
2025-04-17,195.944672,197.784954,193.398129,196.163517,52164700,0.013950,205.117209,220.646036,0.803487
2025-04-21,192.144760,192.781396,188.812362,192.254183,46742500,-0.019393,203.868308,219.854142,0.800924
...,...,...,...,...,...,...,...,...,...
2026-07-01,294.380005,296.589996,289.200012,293.440002,50164200,0.017349,294.884000,292.602499,0.342462
2026-07-02,308.630005,309.420013,293.679993,294.119995,75352800,0.048407,294.802499,293.456599,0.384440
2026-07-06,312.660004,314.200012,307.000000,307.359985,53590000,0.013058,294.873999,294.251427,0.387112
2026-07-07,310.660004,315.480011,310.149994,315.290009,42490000,-0.006397,295.039999,295.001061,0.384992
2026-07-08,313.390015,314.820007,307.049988,311.910004,41299400,0.008788,295.632500,295.852651,0.378697

In [12]:
fig = go.Figure()

fig.add_trace(go.Scatter(x=data.index, y=data['Close'],
              name='Close', mode='lines'))

fig.add_trace(go.Scatter(x=data.index, y=data['Volatility'],
              name='Volatility (20d)', mode='lines', yaxis='y2'))

fig.update_layout(
    title='AAPL Price & Volatility',
    yaxis2=dict(overlaying='y', side='right'),  # second y-axis
    template='plotly_dark'
)
fig.show()


# **TENDENCIES SPOTTED**

1)The price tends to go up after a drop in volatility

2)The trend becomes stronger when volatility consolidates

3)Volatility spikes usually happen after a big price drop

In [13]:
volat_testdata = data.copy()
volat_testdata['Vol_MA'] = volat_testdata['Volatility'].rolling(20).mean()
volat_testdata['Vol_drop'] = volat_testdata['Volatility'] < volat_testdata['Vol_MA']
volat_testdata['Price after 5d'] = volat_testdata['Returns'].shift(-5)
volat_testdata.dropna(inplace=True)
volat_testdata

Price,Close,High,Low,Open,Volume,Returns,SMA_20,SMA_50,Volatility,Vol_MA,Vol_drop,Price after 5d
Date,,,,,,,,,,,,
2025-05-12,209.957047,210.435161,205.933017,210.136343,63775800,0.063146,202.147722,209.314560,0.384037,0.720324,True,-0.011739
2025-05-13,212.088608,212.556752,208.174144,209.598486,51909300,0.010152,202.679375,208.820754,0.378671,0.699656,True,-0.009196
2025-05-14,211.490967,213.094605,209.747882,211.590563,49325800,-0.002818,203.200046,208.356774,0.378842,0.679006,True,-0.023059
2025-05-15,210.614426,212.118468,208.711970,210.116401,45029500,-0.004145,204.068320,207.879044,0.346787,0.656295,True,-0.003612
2025-05-16,210.425201,211.730038,208.941099,211.520861,54737900,-0.000898,204.792347,207.405685,0.345444,0.633393,True,-0.030244
...,...,...,...,...,...,...,...,...,...,...,...,...
2026-06-24,293.079987,299.700012,292.940002,295.359985,53081900,-0.004145,301.510002,290.728578,0.241487,0.212710,False,0.017349
2026-06-25,275.149994,288.799988,273.750000,287.399994,107013700,-0.061178,299.725002,291.059743,0.315316,0.219773,False,0.048407
2026-06-26,283.779999,285.950012,274.209991,275.000000,261775500,0.031365,298.288501,291.411648,0.340162,0.228234,False,0.013058
2026-06-29,281.739990,288.369995,279.850006,286.730011,66427000,-0.007189,296.772501,291.783297,0.340069,0.236561,False,-0.006397
2026-06-30,289.359985,289.940002,280.700012,281.170013,65100200,0.027046,295.925000,292.170872,0.354057,0.245812,False,0.008788

In [14]:
volat_testdata.groupby('Vol_drop')['Price after 5d'].mean()

Vol_drop
False    0.002023
True     0.001202
Name: Price after 5d, dtype: float64

In [17]:
volat_testdata

Price,Close,High,Low,Open,Volume,Returns,SMA_20,SMA_50,Volatility,Vol_MA,Vol_drop,Price after 5d,Uptrend
Date,,,,,,,,,,,,,
2025-05-12,209.957047,210.435161,205.933017,210.136343,63775800,0.063146,202.147722,209.314560,0.384037,0.720324,True,-0.011739,True
2025-05-13,212.088608,212.556752,208.174144,209.598486,51909300,0.010152,202.679375,208.820754,0.378671,0.699656,True,-0.009196,True
2025-05-14,211.490967,213.094605,209.747882,211.590563,49325800,-0.002818,203.200046,208.356774,0.378842,0.679006,True,-0.023059,True
2025-05-15,210.614426,212.118468,208.711970,210.116401,45029500,-0.004145,204.068320,207.879044,0.346787,0.656295,True,-0.003612,True
2025-05-16,210.425201,211.730038,208.941099,211.520861,54737900,-0.000898,204.792347,207.405685,0.345444,0.633393,True,-0.030244,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-06-24,293.079987,299.700012,292.940002,295.359985,53081900,-0.004145,301.510002,290.728578,0.241487,0.212710,False,0.017349,True
2026-06-25,275.149994,288.799988,273.750000,287.399994,107013700,-0.061178,299.725002,291.059743,0.315316,0.219773,False,0.048407,False
2026-06-26,283.779999,285.950012,274.209991,275.000000,261775500,0.031365,298.288501,291.411648,0.340162,0.228234,False,0.013058,False
2026-06-29,281.739990,288.369995,279.850006,286.730011,66427000,-0.007189,296.772501,291.783297,0.340069,0.236561,False,-0.006397,False
2026-06-30,289.359985,289.940002,280.700012,281.170013,65100200,0.027046,295.925000,292.170872,0.354057,0.245812,False,0.008788,False

In [20]:

volat_testdata['Signal'] = (volat_testdata['Vol_drop']) & (volat_testdata['Uptrend'])
volat_testdata

Price,Close,High,Low,Open,Volume,Returns,SMA_20,SMA_50,Volatility,Vol_MA,Vol_drop,Price after 5d,Uptrend,Signal
Date,,,,,,,,,,,,,,
2025-05-12,209.957047,210.435161,205.933017,210.136343,63775800,0.063146,202.147722,209.314560,0.384037,0.720324,True,-0.011739,True,True
2025-05-13,212.088608,212.556752,208.174144,209.598486,51909300,0.010152,202.679375,208.820754,0.378671,0.699656,True,-0.009196,True,True
2025-05-14,211.490967,213.094605,209.747882,211.590563,49325800,-0.002818,203.200046,208.356774,0.378842,0.679006,True,-0.023059,True,True
2025-05-15,210.614426,212.118468,208.711970,210.116401,45029500,-0.004145,204.068320,207.879044,0.346787,0.656295,True,-0.003612,True,True
2025-05-16,210.425201,211.730038,208.941099,211.520861,54737900,-0.000898,204.792347,207.405685,0.345444,0.633393,True,-0.030244,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-06-24,293.079987,299.700012,292.940002,295.359985,53081900,-0.004145,301.510002,290.728578,0.241487,0.212710,False,0.017349,True,False
2026-06-25,275.149994,288.799988,273.750000,287.399994,107013700,-0.061178,299.725002,291.059743,0.315316,0.219773,False,0.048407,False,False
2026-06-26,283.779999,285.950012,274.209991,275.000000,261775500,0.031365,298.288501,291.411648,0.340162,0.228234,False,0.013058,False,False
2026-06-29,281.739990,288.369995,279.850006,286.730011,66427000,-0.007189,296.772501,291.783297,0.340069,0.236561,False,-0.006397,False,False
2026-06-30,289.359985,289.940002,280.700012,281.170013,65100200,0.027046,295.925000,292.170872,0.354057,0.245812,False,0.008788,False,False

In [21]:
volat_testdata.groupby(['Uptrend','Signal'])['Price after 5d'].mean()

Uptrend  Signal
False    False     0.003050
True     False     0.000067
         True      0.001288
Name: Price after 5d, dtype: float64