In [2]:
import pandas as pd
import yfinance as yf
import numpy as np
from plotly.subplots import make_subplots
import plotly.graph_objects as go

In [3]:
data = yf.download("AAPL",start='2025-01-01')
data.columns = data.columns.get_level_values(0)  # flatten to single level
data

[*********************100%***********************]  1 of 1 completed

Price            Close        High         Low        Open    Volume
Date
2025-01-02  242.301926  247.518596  240.284814  247.349662  55740700
2025-01-03  241.815018  242.629804  240.354349  241.815018  40244100
2025-01-06  243.444626  245.759836  241.656050  242.759004  45045600
2025-01-07  240.672348  243.991141  239.817807  241.437449  40856000
2025-01-08  241.159210  242.162808  238.526040  240.384163  37628900
...                ...         ...         ...         ...       ...
2026-07-23  321.660004  323.299988  319.350006  321.730011  40840800
2026-07-24  333.019989  334.369995  321.619995  321.790009  47489400
2026-07-27  336.910004  339.570007  334.019989  334.540009  49604300
2026-07-28  340.079987  342.890015  335.600006  340.029999  51859000
2026-07-29  338.190002  344.570007  337.350006  339.730011  55929000

[393 rows x 5 columns]

In [4]:
data['Returns'] = data['Close'].pct_change()
data = data.dropna()
data

Price            Close        High         Low        Open    Volume   Returns
Date
2025-01-03  241.815018  242.629804  240.354349  241.815018  40244100 -0.002010
2025-01-06  243.444626  245.759836  241.656050  242.759004  45045600  0.006739
2025-01-07  240.672348  243.991141  239.817807  241.437449  40856000 -0.011388
2025-01-08  241.159210  242.162808  238.526040  240.384163  37628900  0.002023
2025-01-10  235.346375  238.635359  231.520810  238.486302  61710900 -0.024104
...                ...         ...         ...         ...       ...       ...
2026-07-23  321.660004  323.299988  319.350006  321.730011  40840800 -0.012980
2026-07-24  333.019989  334.369995  321.619995  321.790009  47489400  0.035317
2026-07-27  336.910004  339.570007  334.019989  334.540009  49604300  0.011681
2026-07-28  340.079987  342.890015  335.600006  340.029999  51859000  0.009409
2026-07-29  338.190002  344.570007  337.350006  339.730011  55929000 -0.005557

[392 rows x 6 columns]

# **SMA ANALYSIS**

In [5]:
data['SMA_20'] = data['Close'].rolling(20).mean()
data['SMA_50'] = data['Close'].rolling(50).mean()

/var/folders/3f/1m46pnxd04q1x1ktf6jcs_fr0000gn/T/ipykernel_35342/2929945010.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['SMA_20'] = data['Close'].rolling(20).mean()
/var/folders/3f/1m46pnxd04q1x1ktf6jcs_fr0000gn/T/ipykernel_35342/2929945010.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['SMA_50'] = data['Close'].rolling(50).mean()

In [6]:
data

Price,Close,High,Low,Open,Volume,Returns,SMA_20,SMA_50
Date,,,,,,,,
2025-01-03,241.815018,242.629804,240.354349,241.815018,40244100,-0.002010,NaN,NaN
2025-01-06,243.444626,245.759836,241.656050,242.759004,45045600,0.006739,NaN,NaN
2025-01-07,240.672348,243.991141,239.817807,241.437449,40856000,-0.011388,NaN,NaN
2025-01-08,241.159210,242.162808,238.526040,240.384163,37628900,0.002023,NaN,NaN
2025-01-10,235.346375,238.635359,231.520810,238.486302,61710900,-0.024104,NaN,NaN
...,...,...,...,...,...,...,...,...
2026-07-23,321.660004,323.299988,319.350006,321.730011,40840800,-0.012980,311.4920,305.4670
2026-07-24,333.019989,334.369995,321.619995,321.790009,47489400,0.035317,314.3855,306.2314
2026-07-27,336.910004,339.570007,334.019989,334.540009,49604300,0.011681,317.0420,306.9922
2026-07-28,340.079987,342.890015,335.600006,340.029999,51859000,0.009409,319.9590,307.8296
2026-07-29,338.190002,344.570007,337.350006,339.730011,55929000,-0.005557,322.4005,308.5888

In [7]:
data.dropna(inplace=True)

/var/folders/3f/1m46pnxd04q1x1ktf6jcs_fr0000gn/T/ipykernel_35342/1368182302.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.dropna(inplace=True)

In [8]:
data

Price,Close,High,Low,Open,Volume,Returns,SMA_20,SMA_50
Date,,,,,,,,
2025-03-18,211.572113,214.019175,210.378423,213.034388,42432400,-0.006122,231.235705,232.228110
2025-03-19,214.108704,217.610192,212.626530,213.094060,54385400,0.011989,229.761992,231.673983
2025-03-20,212.974701,216.346883,211.104577,212.865278,48862900,-0.005296,228.183831,231.064585
2025-03-21,217.122772,217.689768,210.169506,210.448033,94127800,0.019477,226.827000,230.593593
2025-03-24,219.569839,220.315897,217.431146,219.838425,44299500,0.011270,225.515430,230.161806
...,...,...,...,...,...,...,...,...
2026-07-23,321.660004,323.299988,319.350006,321.730011,40840800,-0.012980,311.492000,305.467000
2026-07-24,333.019989,334.369995,321.619995,321.790009,47489400,0.035317,314.385500,306.231400
2026-07-27,336.910004,339.570007,334.019989,334.540009,49604300,0.011681,317.042000,306.992200
2026-07-28,340.079987,342.890015,335.600006,340.029999,51859000,0.009409,319.959000,307.829600
2026-07-29,338.190002,344.570007,337.350006,339.730011,55929000,-0.005557,322.400500,308.588800

In [9]:
fig = make_subplots(rows=2,cols=1)
fig.add_trace(go.Candlestick(x=data.index,open=data['Open'],high=data['High'],low=data['Low'],close=data['Close'],name='Closing Price'),row=1,col=1)
fig.add_trace(go.Scatter(x=data.index,y=data['SMA_20'],name='SMA_20',mode='lines'),row=1,col=1)
fig.add_trace(go.Scatter(x=data.index,y=data['SMA_50'],name='SMA_50',mode='lines'),row=1,col=1)
fig.update_layout(
    height = 600,
    width=800,
    title='AAPL Price with Moving Averages',
    xaxis_title='Date',
    yaxis_title='Price (USD)',
    template='plotly_dark'  # looks clean
)
fig.add_trace(go.Bar(x=data.index,y=data['Volume'],name='Volume'),row=2,col=1)
fig.show()

# **TENDENCIES NOTED FROM THE CHART:**
1)The price tends to go up when the SMA20 marks overtakes SMA50.This was noticed on **17 July 2025** when the overall trend was upwards all the way until **6 January 2026** when the SMA divergence finished

2)The price tends to 'bounce' off the SMA50 line which proves the hypothesis of SMA having an impact on the price action

In [10]:
data

Price,Close,High,Low,Open,Volume,Returns,SMA_20,SMA_50
Date,,,,,,,,
2025-03-18,211.572113,214.019175,210.378423,213.034388,42432400,-0.006122,231.235705,232.228110
2025-03-19,214.108704,217.610192,212.626530,213.094060,54385400,0.011989,229.761992,231.673983
2025-03-20,212.974701,216.346883,211.104577,212.865278,48862900,-0.005296,228.183831,231.064585
2025-03-21,217.122772,217.689768,210.169506,210.448033,94127800,0.019477,226.827000,230.593593
2025-03-24,219.569839,220.315897,217.431146,219.838425,44299500,0.011270,225.515430,230.161806
...,...,...,...,...,...,...,...,...
2026-07-23,321.660004,323.299988,319.350006,321.730011,40840800,-0.012980,311.492000,305.467000
2026-07-24,333.019989,334.369995,321.619995,321.790009,47489400,0.035317,314.385500,306.231400
2026-07-27,336.910004,339.570007,334.019989,334.540009,49604300,0.011681,317.042000,306.992200
2026-07-28,340.079987,342.890015,335.600006,340.029999,51859000,0.009409,319.959000,307.829600
2026-07-29,338.190002,344.570007,337.350006,339.730011,55929000,-0.005557,322.400500,308.588800

# **VOLATILITY ANALYSIS**

In [11]:
data['Volatility'] = data['Returns'].rolling(20).std() * (252 ** 0.5)
data.dropna(inplace=True)
data

/var/folders/3f/1m46pnxd04q1x1ktf6jcs_fr0000gn/T/ipykernel_35342/4174629229.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Volatility'] = data['Returns'].rolling(20).std() * (252 ** 0.5)
/var/folders/3f/1m46pnxd04q1x1ktf6jcs_fr0000gn/T/ipykernel_35342/4174629229.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.dropna(inplace=True)

Price,Close,High,Low,Open,Volume,Returns,SMA_20,SMA_50,Volatility
Date,,,,,,,,,
2025-04-14,201.455551,211.820781,200.102699,210.328665,101352900,0.022054,207.536428,222.618188,0.792023
2025-04-15,201.077545,202.440340,198.749848,200.799018,51343900,-0.001876,207.011700,222.108489,0.791845
2025-04-16,193.248932,199.645129,191.358909,197.317431,59732400,-0.038933,205.968711,221.347026,0.801011
2025-04-17,195.944656,197.784939,193.398114,196.163501,52164700,0.013949,205.117209,220.646036,0.803487
2025-04-21,192.144760,192.781396,188.812362,192.254183,46742500,-0.019393,203.868308,219.854143,0.800924
...,...,...,...,...,...,...,...,...,...
2026-07-23,321.660004,323.299988,319.350006,321.730011,40840800,-0.012980,311.492000,305.467000,0.377413
2026-07-24,333.019989,334.369995,321.619995,321.790009,47489400,0.035317,314.385500,306.231400,0.300899
2026-07-27,336.910004,339.570007,334.019989,334.540009,49604300,0.011681,317.042000,306.992200,0.290070
2026-07-28,340.079987,342.890015,335.600006,340.029999,51859000,0.009409,319.959000,307.829600,0.283872
2026-07-29,338.190002,344.570007,337.350006,339.730011,55929000,-0.005557,322.400500,308.588800,0.280877

In [12]:
fig = go.Figure()

fig.add_trace(go.Scatter(x=data.index, y=data['Close'],
              name='Close', mode='lines'))

fig.add_trace(go.Scatter(x=data.index, y=data['Volatility'],
              name='Volatility (20d)', mode='lines', yaxis='y2'))

fig.update_layout(
    title='AAPL Price & Volatility',
    yaxis2=dict(overlaying='y', side='right'),  # second y-axis
    template='plotly_dark'
)
fig.show()


# **TENDENCIES SPOTTED**

1)The price tends to go up after a drop in volatility

2)The trend becomes stronger when volatility consolidates

3)Volatility spikes usually happen after a big price drop

In [13]:
volat_testdata = data.copy()
volat_testdata['Vol_MA'] = volat_testdata['Volatility'].rolling(20).mean()
volat_testdata['Vol_drop'] = volat_testdata['Volatility'] < volat_testdata['Vol_MA']
volat_testdata['Price after 5d'] = volat_testdata['Returns'].shift(-5)
volat_testdata.dropna(inplace=True)
volat_testdata

Price,Close,High,Low,Open,Volume,Returns,SMA_20,SMA_50,Volatility,Vol_MA,Vol_drop,Price after 5d
Date,,,,,,,,,,,,
2025-05-12,209.957047,210.435161,205.933017,210.136343,63775800,0.063146,202.147718,209.314560,0.384037,0.720324,True,-0.011739
2025-05-13,212.088593,212.556737,208.174129,209.598471,51909300,0.010152,202.679370,208.820753,0.378671,0.699656,True,-0.009196
2025-05-14,211.490967,213.094605,209.747882,211.590563,49325800,-0.002818,203.200041,208.356774,0.378842,0.679006,True,-0.023059
2025-05-15,210.614426,212.118468,208.711970,210.116401,45029500,-0.004145,204.068316,207.879044,0.346787,0.656295,True,-0.003612
2025-05-16,210.425186,211.730022,208.941084,211.520846,54737900,-0.000899,204.792342,207.405685,0.345444,0.633393,True,-0.030244
...,...,...,...,...,...,...,...,...,...,...,...,...
2026-07-16,333.260010,334.679993,326.790009,328.010010,62970600,0.017588,303.628500,301.635984,0.367702,0.329187,False,-0.012980
2026-07-17,333.739990,334.989990,329.000000,331.980011,63407100,0.001440,305.517999,302.632416,0.362852,0.334828,False,0.035317
2026-07-20,326.589996,333.709991,323.679993,333.510010,53468000,-0.021424,306.946999,303.419308,0.375896,0.341221,False,0.011681
2026-07-21,327.739990,329.600006,322.220001,323.130005,41338900,0.003521,308.483498,304.230600,0.374694,0.347680,False,0.009409
2026-07-22,325.890015,329.000000,323.339996,327.869995,38755900,-0.005645,310.062999,304.887400,0.373130,0.354266,False,-0.005557

In [14]:
volat_testdata.groupby('Vol_drop')['Price after 5d'].mean()

Vol_drop
False    0.002416
True     0.001202
Name: Price after 5d, dtype: float64

In [15]:
volat_testdata

Price,Close,High,Low,Open,Volume,Returns,SMA_20,SMA_50,Volatility,Vol_MA,Vol_drop,Price after 5d
Date,,,,,,,,,,,,
2025-05-12,209.957047,210.435161,205.933017,210.136343,63775800,0.063146,202.147718,209.314560,0.384037,0.720324,True,-0.011739
2025-05-13,212.088593,212.556737,208.174129,209.598471,51909300,0.010152,202.679370,208.820753,0.378671,0.699656,True,-0.009196
2025-05-14,211.490967,213.094605,209.747882,211.590563,49325800,-0.002818,203.200041,208.356774,0.378842,0.679006,True,-0.023059
2025-05-15,210.614426,212.118468,208.711970,210.116401,45029500,-0.004145,204.068316,207.879044,0.346787,0.656295,True,-0.003612
2025-05-16,210.425186,211.730022,208.941084,211.520846,54737900,-0.000899,204.792342,207.405685,0.345444,0.633393,True,-0.030244
...,...,...,...,...,...,...,...,...,...,...,...,...
2026-07-16,333.260010,334.679993,326.790009,328.010010,62970600,0.017588,303.628500,301.635984,0.367702,0.329187,False,-0.012980
2026-07-17,333.739990,334.989990,329.000000,331.980011,63407100,0.001440,305.517999,302.632416,0.362852,0.334828,False,0.035317
2026-07-20,326.589996,333.709991,323.679993,333.510010,53468000,-0.021424,306.946999,303.419308,0.375896,0.341221,False,0.011681
2026-07-21,327.739990,329.600006,322.220001,323.130005,41338900,0.003521,308.483498,304.230600,0.374694,0.347680,False,0.009409
2026-07-22,325.890015,329.000000,323.339996,327.869995,38755900,-0.005645,310.062999,304.887400,0.373130,0.354266,False,-0.005557

In [18]:
data

Price,Close,High,Low,Open,Volume,Returns,SMA_20,SMA_50,Volatility
Date,,,,,,,,,
2025-04-14,201.455551,211.820781,200.102699,210.328665,101352900,0.022054,207.536428,222.618188,0.792023
2025-04-15,201.077545,202.440340,198.749848,200.799018,51343900,-0.001876,207.011700,222.108489,0.791845
2025-04-16,193.248932,199.645129,191.358909,197.317431,59732400,-0.038933,205.968711,221.347026,0.801011
2025-04-17,195.944656,197.784939,193.398114,196.163501,52164700,0.013949,205.117209,220.646036,0.803487
2025-04-21,192.144760,192.781396,188.812362,192.254183,46742500,-0.019393,203.868308,219.854143,0.800924
...,...,...,...,...,...,...,...,...,...
2026-07-23,321.660004,323.299988,319.350006,321.730011,40840800,-0.012980,311.492000,305.467000,0.377413
2026-07-24,333.019989,334.369995,321.619995,321.790009,47489400,0.035317,314.385500,306.231400,0.300899
2026-07-27,336.910004,339.570007,334.019989,334.540009,49604300,0.011681,317.042000,306.992200,0.290070
2026-07-28,340.079987,342.890015,335.600006,340.029999,51859000,0.009409,319.959000,307.829600,0.283872
2026-07-29,338.190002,344.570007,337.350006,339.730011,55929000,-0.005557,322.400500,308.588800,0.280877

In [19]:
sma_strategy = data.copy()

In [20]:
sma_strategy['Signal'] = np.where(sma_strategy['SMA_20'] > sma_strategy['SMA_50'],1,0)
sma_strategy

Price,Close,High,Low,Open,Volume,Returns,SMA_20,SMA_50,Volatility,Signal
Date,,,,,,,,,,
2025-04-14,201.455551,211.820781,200.102699,210.328665,101352900,0.022054,207.536428,222.618188,0.792023,0
2025-04-15,201.077545,202.440340,198.749848,200.799018,51343900,-0.001876,207.011700,222.108489,0.791845,0
2025-04-16,193.248932,199.645129,191.358909,197.317431,59732400,-0.038933,205.968711,221.347026,0.801011,0
2025-04-17,195.944656,197.784939,193.398114,196.163501,52164700,0.013949,205.117209,220.646036,0.803487,0
2025-04-21,192.144760,192.781396,188.812362,192.254183,46742500,-0.019393,203.868308,219.854143,0.800924,0
...,...,...,...,...,...,...,...,...,...,...
2026-07-23,321.660004,323.299988,319.350006,321.730011,40840800,-0.012980,311.492000,305.467000,0.377413,1
2026-07-24,333.019989,334.369995,321.619995,321.790009,47489400,0.035317,314.385500,306.231400,0.300899,1
2026-07-27,336.910004,339.570007,334.019989,334.540009,49604300,0.011681,317.042000,306.992200,0.290070,1
2026-07-28,340.079987,342.890015,335.600006,340.029999,51859000,0.009409,319.959000,307.829600,0.283872,1
2026-07-29,338.190002,344.570007,337.350006,339.730011,55929000,-0.005557,322.400500,308.588800,0.280877,1

In [21]:
sma_strategy['Strategy_Returns'] = sma_strategy['Signal'].shift(1) * sma_strategy['Returns']
sma_strategy

Price,Close,High,Low,Open,Volume,Returns,SMA_20,SMA_50,Volatility,Signal,Strategy_Returns
Date,,,,,,,,,,,
2025-04-14,201.455551,211.820781,200.102699,210.328665,101352900,0.022054,207.536428,222.618188,0.792023,0,NaN
2025-04-15,201.077545,202.440340,198.749848,200.799018,51343900,-0.001876,207.011700,222.108489,0.791845,0,-0.000000
2025-04-16,193.248932,199.645129,191.358909,197.317431,59732400,-0.038933,205.968711,221.347026,0.801011,0,-0.000000
2025-04-17,195.944656,197.784939,193.398114,196.163501,52164700,0.013949,205.117209,220.646036,0.803487,0,0.000000
2025-04-21,192.144760,192.781396,188.812362,192.254183,46742500,-0.019393,203.868308,219.854143,0.800924,0,-0.000000
...,...,...,...,...,...,...,...,...,...,...,...
2026-07-23,321.660004,323.299988,319.350006,321.730011,40840800,-0.012980,311.492000,305.467000,0.377413,1,-0.012980
2026-07-24,333.019989,334.369995,321.619995,321.790009,47489400,0.035317,314.385500,306.231400,0.300899,1,0.035317
2026-07-27,336.910004,339.570007,334.019989,334.540009,49604300,0.011681,317.042000,306.992200,0.290070,1,0.011681
2026-07-28,340.079987,342.890015,335.600006,340.029999,51859000,0.009409,319.959000,307.829600,0.283872,1,0.009409
2026-07-29,338.190002,344.570007,337.350006,339.730011,55929000,-0.005557,322.400500,308.588800,0.280877,1,-0.005557

In [24]:
sma_strategy.groupby('Signal')['Strategy_Returns'].mean()

Signal
0   -0.000276
1    0.001776
Name: Strategy_Returns, dtype: float64

In [25]:
sharpe = (sma_strategy['Strategy_Returns'].mean() /
          sma_strategy['Strategy_Returns'].std() * (252 ** 0.5))
print(f'Sharpe: {sharpe:.2f}')

Sharpe: 1.41

In [26]:
sma_strategy['Equity_Curve'] = (1 + sma_strategy['Strategy_Returns']).cumprod()
sma_strategy['Buy_Hold'] = (1 + sma_strategy['Returns']).cumprod()
sma_strategy

Price,Close,High,Low,Open,Volume,Returns,SMA_20,SMA_50,Volatility,Signal,Strategy_Returns,Equity_Curve,Buy_Hold
Date,,,,,,,,,,,,,
2025-04-14,201.455551,211.820781,200.102699,210.328665,101352900,0.022054,207.536428,222.618188,0.792023,0,NaN,NaN,1.022054
2025-04-15,201.077545,202.440340,198.749848,200.799018,51343900,-0.001876,207.011700,222.108489,0.791845,0,-0.000000,1.000000,1.020136
2025-04-16,193.248932,199.645129,191.358909,197.317431,59732400,-0.038933,205.968711,221.347026,0.801011,0,-0.000000,1.000000,0.980419
2025-04-17,195.944656,197.784939,193.398114,196.163501,52164700,0.013949,205.117209,220.646036,0.803487,0,0.000000,1.000000,0.994095
2025-04-21,192.144760,192.781396,188.812362,192.254183,46742500,-0.019393,203.868308,219.854143,0.800924,0,-0.000000,1.000000,0.974817
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-07-23,321.660004,323.299988,319.350006,321.730011,40840800,-0.012980,311.492000,305.467000,0.377413,1,-0.012980,1.320063,1.631893
2026-07-24,333.019989,334.369995,321.619995,321.790009,47489400,0.035317,314.385500,306.231400,0.300899,1,0.035317,1.366684,1.689526
2026-07-27,336.910004,339.570007,334.019989,334.540009,49604300,0.011681,317.042000,306.992200,0.290070,1,0.011681,1.382648,1.709261
2026-07-28,340.079987,342.890015,335.600006,340.029999,51859000,0.009409,319.959000,307.829600,0.283872,1,0.009409,1.395657,1.725344
2026-07-29,338.190002,344.570007,337.350006,339.730011,55929000,-0.005557,322.400500,308.588800,0.280877,1,-0.005557,1.387901,1.715755

In [27]:
fig = go.Figure()
fig.add_trace(go.Scatter(x=sma_strategy.index,y=sma_strategy['Equity_Curve'],name='Equity Curve',mode='lines'))
fig.add_trace(go.Scatter(x=sma_strategy.index,y=sma_strategy['Buy_Hold'],name='Buy & Hold',mode='lines'))
fig.update_layout(title='Strategy vs Buy & Hold',
                  template='plotly_dark')
fig.show()