In [16]:
import pandas as pd
import yfinance as yf
import numpy as np
from plotly.subplots import make_subplots
import plotly.graph_objects as go

In [17]:
data = yf.download("AAPL",start='2025-01-01')
data.columns = data.columns.get_level_values(0)  # flatten to single level
data

[*********************100%***********************]  1 of 1 completed

Price            Close        High         Low        Open    Volume
Date
2025-01-02  242.301910  247.518580  240.284799  247.349646  55740700
2025-01-03  241.815018  242.629804  240.354349  241.815018  40244100
2025-01-06  243.444626  245.759836  241.656050  242.759004  45045600
2025-01-07  240.672348  243.991141  239.817807  241.437449  40856000
2025-01-08  241.159210  242.162808  238.526040  240.384163  37628900
...                ...         ...         ...         ...       ...
2026-07-01  294.380005  296.589996  289.200012  293.440002  50164200
2026-07-02  308.630005  309.420013  293.679993  294.119995  75352800
2026-07-06  312.660004  314.200012  307.000000  307.359985  53590000
2026-07-07  310.660004  315.480011  310.149994  315.290009  42426500
2026-07-08  313.125000  313.339996  307.051514  311.660004  17649492

[378 rows x 5 columns]

In [18]:
data['Returns'] = data['Close'].pct_change()
data = data.dropna()
data

Price            Close        High         Low        Open    Volume   Returns
Date
2025-01-03  241.815018  242.629804  240.354349  241.815018  40244100 -0.002009
2025-01-06  243.444626  245.759836  241.656050  242.759004  45045600  0.006739
2025-01-07  240.672348  243.991141  239.817807  241.437449  40856000 -0.011388
2025-01-08  241.159210  242.162808  238.526040  240.384163  37628900  0.002023
2025-01-10  235.346359  238.635343  231.520795  238.486286  61710900 -0.024104
...                ...         ...         ...         ...       ...       ...
2026-07-01  294.380005  296.589996  289.200012  293.440002  50164200  0.017349
2026-07-02  308.630005  309.420013  293.679993  294.119995  75352800  0.048407
2026-07-06  312.660004  314.200012  307.000000  307.359985  53590000  0.013058
2026-07-07  310.660004  315.480011  310.149994  315.290009  42426500 -0.006397
2026-07-08  313.125000  313.339996  307.051514  311.660004  17649492  0.007935

[377 rows x 6 columns]

# **SMA ANALYSIS**

In [19]:
data['SMA_20'] = data['Close'].rolling(20).mean()
data['SMA_50'] = data['Close'].rolling(50).mean()

/var/folders/3f/1m46pnxd04q1x1ktf6jcs_fr0000gn/T/ipykernel_28167/2929945010.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['SMA_20'] = data['Close'].rolling(20).mean()
/var/folders/3f/1m46pnxd04q1x1ktf6jcs_fr0000gn/T/ipykernel_28167/2929945010.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['SMA_50'] = data['Close'].rolling(50).mean()

In [20]:
data

Price,Close,High,Low,Open,Volume,Returns,SMA_20,SMA_50
Date,,,,,,,,
2025-01-03,241.815018,242.629804,240.354349,241.815018,40244100,-0.002009,NaN,NaN
2025-01-06,243.444626,245.759836,241.656050,242.759004,45045600,0.006739,NaN,NaN
2025-01-07,240.672348,243.991141,239.817807,241.437449,40856000,-0.011388,NaN,NaN
2025-01-08,241.159210,242.162808,238.526040,240.384163,37628900,0.002023,NaN,NaN
2025-01-10,235.346359,238.635343,231.520795,238.486286,61710900,-0.024104,NaN,NaN
...,...,...,...,...,...,...,...,...
2026-07-01,294.380005,296.589996,289.200012,293.440002,50164200,0.017349,294.884000,292.602499
2026-07-02,308.630005,309.420013,293.679993,294.119995,75352800,0.048407,294.802499,293.456599
2026-07-06,312.660004,314.200012,307.000000,307.359985,53590000,0.013058,294.873999,294.251427
2026-07-07,310.660004,315.480011,310.149994,315.290009,42426500,-0.006397,295.039999,295.001061
2026-07-08,313.125000,313.339996,307.051514,311.660004,17649492,0.007935,295.619249,295.847351

In [21]:
data.dropna(inplace=True)

/var/folders/3f/1m46pnxd04q1x1ktf6jcs_fr0000gn/T/ipykernel_28167/1368182302.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.dropna(inplace=True)

In [22]:
data

Price,Close,High,Low,Open,Volume,Returns,SMA_20,SMA_50
Date,,,,,,,,
2025-03-18,211.572098,214.019159,210.378408,213.034373,42432400,-0.006122,231.235704,232.228112
2025-03-19,214.108704,217.610192,212.626530,213.094060,54385400,0.011989,229.761991,231.673986
2025-03-20,212.974716,216.346898,211.104592,212.865294,48862900,-0.005296,228.183832,231.064587
2025-03-21,217.122772,217.689768,210.169506,210.448033,94127800,0.019477,226.827001,230.593596
2025-03-24,219.569839,220.315897,217.431146,219.838425,44299500,0.011270,225.515430,230.161808
...,...,...,...,...,...,...,...,...
2026-07-01,294.380005,296.589996,289.200012,293.440002,50164200,0.017349,294.884000,292.602499
2026-07-02,308.630005,309.420013,293.679993,294.119995,75352800,0.048407,294.802499,293.456599
2026-07-06,312.660004,314.200012,307.000000,307.359985,53590000,0.013058,294.873999,294.251427
2026-07-07,310.660004,315.480011,310.149994,315.290009,42426500,-0.006397,295.039999,295.001061
2026-07-08,313.125000,313.339996,307.051514,311.660004,17649492,0.007935,295.619249,295.847351

In [23]:
fig = make_subplots(rows=2,cols=1)
fig.add_trace(go.Candlestick(x=data.index,open=data['Open'],high=data['High'],low=data['Low'],close=data['Close'],name='Closing Price'),row=1,col=1)
fig.add_trace(go.Scatter(x=data.index,y=data['SMA_20'],name='SMA_20',mode='lines'),row=1,col=1)
fig.add_trace(go.Scatter(x=data.index,y=data['SMA_50'],name='SMA_50',mode='lines'),row=1,col=1)
fig.update_layout(
    height = 600,
    width=800,
    title='AAPL Price with Moving Averages',
    xaxis_title='Date',
    yaxis_title='Price (USD)',
    template='plotly_dark'  # looks clean
)
fig.add_trace(go.Bar(x=data.index,y=data['Volume'],name='Volume'),row=2,col=1)
fig.show()

# **TENDENCIES NOTED FROM THE CHART:**
1)The price tends to go up when the SMA20 marks overtakes SMA50.This was noticed on **17 July 2025** when the overall trend was upwards all the way until **6 January 2026** when the SMA divergence finished

2)The price tends to 'bounce' off the SMA50 line which proves the hypothesis of SMA having an impact on the price action

In [24]:
data

Price,Close,High,Low,Open,Volume,Returns,SMA_20,SMA_50
Date,,,,,,,,
2025-03-18,211.572098,214.019159,210.378408,213.034373,42432400,-0.006122,231.235704,232.228112
2025-03-19,214.108704,217.610192,212.626530,213.094060,54385400,0.011989,229.761991,231.673986
2025-03-20,212.974716,216.346898,211.104592,212.865294,48862900,-0.005296,228.183832,231.064587
2025-03-21,217.122772,217.689768,210.169506,210.448033,94127800,0.019477,226.827001,230.593596
2025-03-24,219.569839,220.315897,217.431146,219.838425,44299500,0.011270,225.515430,230.161808
...,...,...,...,...,...,...,...,...
2026-07-01,294.380005,296.589996,289.200012,293.440002,50164200,0.017349,294.884000,292.602499
2026-07-02,308.630005,309.420013,293.679993,294.119995,75352800,0.048407,294.802499,293.456599
2026-07-06,312.660004,314.200012,307.000000,307.359985,53590000,0.013058,294.873999,294.251427
2026-07-07,310.660004,315.480011,310.149994,315.290009,42426500,-0.006397,295.039999,295.001061
2026-07-08,313.125000,313.339996,307.051514,311.660004,17649492,0.007935,295.619249,295.847351

# **VOLATILITY ANALYSIS**

In [25]:
data['Volatility'] = data['Returns'].rolling(20).std() * (252 ** 0.5)
data.dropna(inplace=True)
data

/var/folders/3f/1m46pnxd04q1x1ktf6jcs_fr0000gn/T/ipykernel_28167/4174629229.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Volatility'] = data['Returns'].rolling(20).std() * (252 ** 0.5)
/var/folders/3f/1m46pnxd04q1x1ktf6jcs_fr0000gn/T/ipykernel_28167/4174629229.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.dropna(inplace=True)

Price,Close,High,Low,Open,Volume,Returns,SMA_20,SMA_50,Volatility
Date,,,,,,,,,
2025-04-14,201.455566,211.820797,200.102714,210.328681,101352900,0.022054,207.536424,222.618186,0.792023
2025-04-15,201.077545,202.440340,198.749848,200.799018,51343900,-0.001876,207.011697,222.108487,0.791845
2025-04-16,193.248917,199.645113,191.358894,197.317416,59732400,-0.038933,205.968707,221.347024,0.801011
2025-04-17,195.944656,197.784939,193.398114,196.163501,52164700,0.013950,205.117204,220.646034,0.803487
2025-04-21,192.144760,192.781396,188.812362,192.254183,46742500,-0.019393,203.868304,219.854141,0.800924
...,...,...,...,...,...,...,...,...,...
2026-07-01,294.380005,296.589996,289.200012,293.440002,50164200,0.017349,294.884000,292.602499,0.342462
2026-07-02,308.630005,309.420013,293.679993,294.119995,75352800,0.048407,294.802499,293.456599,0.384440
2026-07-06,312.660004,314.200012,307.000000,307.359985,53590000,0.013058,294.873999,294.251427,0.387112
2026-07-07,310.660004,315.480011,310.149994,315.290009,42426500,-0.006397,295.039999,295.001061,0.384992
2026-07-08,313.125000,313.339996,307.051514,311.660004,17649492,0.007935,295.619249,295.847351,0.378512

In [26]:
fig = go.Figure()

fig.add_trace(go.Scatter(x=data.index, y=data['Close'],
              name='Close', mode='lines'))

fig.add_trace(go.Scatter(x=data.index, y=data['Volatility'],
              name='Volatility (20d)', mode='lines', yaxis='y2'))

fig.update_layout(
    title='AAPL Price & Volatility',
    yaxis2=dict(overlaying='y', side='right'),  # second y-axis
    template='plotly_dark'
)
fig.show()


# **TENDENCIES SPOTTED**

1)The price tends to go up after a drop in volatility

2)The trend becomes stronger when volatility consolidates

3)Volatility spikes usually happen after a big price drop

In [30]:
volat_testdata = data.copy()
volat_testdata['Vol_MA'] = volat_testdata['Volatility'].rolling(20).mean()
volat_testdata['Vol_drop'] = volat_testdata['Volatility'] < volat_testdata['Vol_MA']
volat_testdata['Price after 5d'] = volat_testdata['Returns'].shift(-5)
volat_testdata.dropna(inplace=True)
volat_testdata

Price,Close,High,Low,Open,Volume,Returns,SMA_20,SMA_50,Volatility,Vol_MA,Vol_drop,Price after 5d
Date,,,,,,,,,,,,
2025-07-08,209.180130,210.594517,207.626297,209.269786,42848900,0.000286,201.927412,202.994305,0.199469,0.204332,True,0.002349
2025-07-09,210.305664,210.494916,206.401156,208.702025,48749400,0.005381,202.409998,203.036818,0.193145,0.198687,True,0.005021
2025-07-10,211.570663,212.636427,209.200063,209.678162,44443600,0.006015,202.895074,203.087521,0.193135,0.198273,True,-0.000666
2025-07-11,210.325607,211.291776,209.030741,209.737942,39765800,-0.005885,203.511628,203.092035,0.178612,0.196950,True,0.005523
2025-07-14,207.795624,210.076583,206.719890,209.100445,38840100,-0.012029,203.980767,203.020286,0.186513,0.195977,True,0.006156
...,...,...,...,...,...,...,...,...,...,...,...,...
2026-06-09,290.549988,300.750000,287.779999,300.279999,70108800,-0.036446,304.558000,282.902386,0.233429,0.199837,False,0.009513
2026-06-10,291.579987,294.750000,287.380005,290.739990,52793300,0.003545,304.397000,283.805926,0.232218,0.198443,False,-0.010994
2026-06-11,295.630005,297.000000,289.589996,293.720001,42572500,0.013890,304.235001,284.647399,0.232287,0.197674,False,0.006961
2026-06-12,291.130005,297.140015,289.619995,296.029999,38742100,-0.015222,303.881001,285.362105,0.238119,0.197517,False,-0.003356
2026-06-15,296.420013,297.779999,291.700012,294.119995,45732600,0.018171,303.690501,286.176816,0.246405,0.198339,False,-0.009124

In [31]:
volat_testdata.groupby('Vol_drop')['Price after 5d'].mean()

Vol_drop
False    0.001540
True     0.001596
Name: Price after 5d, dtype: float64